import os
import re
import asyncio
import logging
from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup
from telegram.ext import ApplicationBuilder, CommandHandler, MessageHandler, filters, ContextTypes
from youtube_transcript_api import YouTubeTranscriptApi
import google.generativeai as genai
from keep_alive import keep_alive

# 1. Setup Logging
logging.basicConfig(format='%(asctime)s - %(name)s - %(levelname)s - %(message)s', level=logging.INFO)

# 2. Environment Variables
TOKEN = os.getenv("TELEGRAM_TOKEN")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

# 3. Gemini Setup
genai.configure(api_key=GEMINI_API_KEY)
model = genai.GenerativeModel('gemini-pro')

# 4. Helper Functions
def get_video_id(url):
    pattern = r'(?:https?:\/\/)?(?:www\.)?(?:youtube\.com\/(?:[^\/\n\s]+\/\S+\/|(?:v|e(?:mbed)?)\/|\S*?[?&]v=)|youtu\.be\/)([a-zA-Z0-9_-]{11})'
    match = re.search(pattern, url)
    return match.group(1) if match else None

# 5. Command Handlers
async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    # Animation/GIF ki jagah ek mast Welcome message with Buttons
    welcome_text = (
        "👋 *Ram Ram Bhai! Welcome to YT Summarizer AI*\n\n"
        "Main kisi bhi YouTube video ka nichod (summary) nikaal sakta hoon.\n\n"
        "🚀 *Kaise use karein?*\n"
        "Bas link bhejo aur magic dekho!"
    )
    keyboard = [
        [InlineKeyboardButton("Help ❓", callback_data='help'),
         InlineKeyboardButton("About 🤖", callback_data='about')]
    ]
    reply_markup = InlineKeyboardMarkup(keyboard)
    
    # Aap yahan koi bhi direct image link daal sakte ho animation ke liye
    await update.message.reply_photo(
        photo="https://img.freepik.com/free-vector/ai-technology-brain-background-digital-transformation-concept_53876-117538.jpg",
        caption=welcome_text,
        parse_mode='Markdown',
        reply_markup=reply_markup
    )

async def help_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    help_text = (
        "📖 *Help Menu:*\n\n"
        "1️⃣ /start - Bot shuru karne ke liye.\n"
        "2️⃣ /help - Ye menu dekhne ke liye.\n"
        "3️⃣ /status - Check karne ke liye bot sahi chal raha hai ya nahi.\n\n"
        "💡 *Tip:* Sirf wahi video summary hogi jisme English ya Hindi subtitles honge."
    )
    await update.message.reply_text(help_text, parse_mode='Markdown')

async def status(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text("✅ *System Status:* Bot Ekdum Mast Chal Raha Hai!", parse_mode='Markdown')

async def handle_message(update: Update, context: ContextTypes.DEFAULT_TYPE):
    text = update.message.text
    video_id = get_video_id(text)
    
    if video_id:
        status_msg = await update.message.reply_text("⏳ *Video mil gayi! Dimag laga raha hoon...*", parse_mode='Markdown')
        
        try:
            transcript_list = YouTubeTranscriptApi.get_transcript(video_id, languages=['en', 'hi'])
            transcript = " ".join([t['text'] for t in transcript_list])
            
            await status_msg.edit_text("✍️ *Transcription mil gayi! Ab summary likh raha hoon...*", parse_mode='Markdown')
            
            prompt = f"Summarize this YouTube video in 5 catchy bullet points in Hinglish. Make it professional yet easy to understand:\n\n{transcript[:30000]}"
            response = model.generate_content(prompt)
            
            final_summary = f"📊 *VIDEO SUMMARY*\n\n{response.text}\n\n✨ *Generated by your AI Buddy*"
            await status_msg.edit_text(final_summary, parse_mode='Markdown')
            
        except Exception as e:
            await status_msg.edit_text("❌ *Error:* Is video ke subtitles band hain ya video bahut lambi hai.")
    else:
        await update.message.reply_text("⚠️ Bhai, ye YouTube link nahi lag raha. Sahi link bhej!")

# 6. Main Execution
if __name__ == '__main__':
    keep_alive() # Render survival trick
    app = ApplicationBuilder().token(TOKEN).build()
    
    app.add_handler(CommandHandler("start", start))
    app.add_handler(CommandHandler("help", help_command))
    app.add_handler(CommandHandler("status", status))
    app.add_handler(MessageHandler(filters.TEXT & (~filters.COMMAND), handle_message))
    
    print("Bot is running...")
    app.run_polling()
